Used ## to comment out file generation and kaggle commit, delete them if needed.

## Building Predictive Models

In [3]:
import pandas as pd
import os
import numpy as np

### Import Data

In [4]:
# set the path of the processed data
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [5]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [7]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

### Data Preperation

In [8]:
X = train_df.loc[:,'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()

/home/kevin/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [9]:
print X.shape, y.shape

(891, 32) (891,)


In [10]:
#error?  see Check Scikit-Learn version, is it even installed?
# train test split
from sklearn.model_selection import train_test_split
#from scikit-learn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(712, 32) (712,)
(179, 32) (179,)


In [11]:
# average survival in train and test
print 'mean survival in train : {0:.3f}'.format(np.mean(y_train))
print 'mean survival in test : {0:.3f}'.format(np.mean(y_test))

mean survival in train : 0.383
mean survival in test : 0.385


#### Check Scikit-Learn Version

In [12]:
import sklearn

In [13]:
sklearn.__version__

'0.20.4'

make sure you have Scikit-Learn v0.19. Else update it and restart kernel. 

In [14]:
#!conda update -y scikit-learn

### Baseline Model

In [15]:
# import function
from sklearn.dummy import DummyClassifier

In [16]:
# create model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)

In [17]:
# train model
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [18]:
print 'score for baseline model : {0:.2f}'.format(model_dummy.score(X_test, y_test))

score for baseline model : 0.61


In [19]:
# peformance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [20]:
# accuracy score
print 'accuracy for baseline model : {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test)))

accuracy for baseline model : 0.61


In [21]:
# confusion matrix
print 'confusion matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test)))

confusion matrix for baseline model: 
 [[110   0]
 [ 69   0]]


In [22]:
# precision and recall scores
print 'precision for baseline model : {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test)))
print 'recall for baseline model : {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test)))

precision for baseline model : 0.00
recall for baseline model : 0.00


/home/kevin/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### First Kaggle  Submission 

In [23]:
# converting to the matrix
#test_X = test_df.as_matrix().astype('float')
test_X = test_df.values.astype('float')

In [24]:
# get predictions
predictions = model_dummy.predict(test_X)

In [25]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions} )

In [26]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [27]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path, '01_dummy.csv')

In [28]:
df_submission.to_csv(submission_file_path, index=False)

In [29]:
def get_submission_file(model, filename):
    # converting to the matrix
#    test_X = test_df.as_matrix().astype('float')
    test_X = test_df.values.astype('float')
    # make predictions
    predictions = model.predict(test_X)
    # submission dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
    # submission file
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path, filename)
    # write to the file
    df_submission.to_csv(submission_file_path, index=False)

In [30]:
# get submission file
##get_submission_file(model_dummy, '01_dummy.csv')

### Logistic Regression Model

In [31]:
# import function
from sklearn.linear_model import LogisticRegression

In [32]:
# create model
model_lr_1 = LogisticRegression(random_state=0)

In [33]:
# train model
model_lr_1.fit(X_train,y_train)

/home/kevin/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [34]:
# evaluate model
print 'score for logistic regression - version 1 : {0:.2f}'.format(model_lr_1.score(X_test, y_test))

score for logistic regression - version 1 : 0.83


In [35]:
# performance metrics
# accuracy
print 'accuracy for logistic regression - version 1 : {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test)))
# confusion matrix
print 'confusion matrix for logistic regression - version 1: \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test)))
# precision 
print 'precision for logistic regression - version 1 : {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test)))
# precision 
print 'recall for logistic regression - version 1 : {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test)))

accuracy for logistic regression - version 1 : 0.83
confusion matrix for logistic regression - version 1: 
 [[95 15]
 [15 54]]
precision for logistic regression - version 1 : 0.78
recall for logistic regression - version 1 : 0.78


In [36]:
# model coefficients
model_lr_1.coef_
#todo - find out what these relate to, maybe loose the meaningless ones for simplicity?

array([[-0.02840734,  0.00455631, -0.50017004,  0.61922842, -0.81414743,
         0.12823264, -0.17253857, -0.3935549 ,  0.52215009,  1.09939126,
         0.40346551, -0.18369315, -0.30021027,  0.96558545,  0.4828179 ,
        -0.34516075,  0.2825859 ,  1.21850072,  0.56334181, -1.4461251 ,
         1.07146231, -0.11345499, -0.47306806,  0.16297319,  0.24746356,
         0.2799826 ,  0.41282325,  0.49202889,  0.46214498,  0.14906872,
         0.37253568,  0.73070692]])

### Second Kaggle Submission

In [37]:
# get submission file
##get_submission_file(model_lr_1, '02_lr.csv')

In [38]:
##!/home/kevin/anaconda3/envs/py27/bin/kaggle competitions submit -c titanic -f /home/kevin/Projects/titanic/data/external/02_lr.csv -m "Logistic Regression v1"

### Part 2 

### Hyperparameter Optimization

In [39]:
# base model 
model_lr = LogisticRegression(random_state=0)

In [40]:
from sklearn.model_selection import GridSearchCV

'C' = Regularization parameter, too high = overfit.  
penalty = L1 / L2 = another reg param

In [41]:
parameters = {'C':[0.9, 1.0, 1.1, 5.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

In [42]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [0.9, 1.0, 1.1, 5.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [43]:
clf.best_params_
#LR1 used C 1.0, penalty l2

{'C': 1.0, 'penalty': 'l1'}

In [44]:
print 'best score : {0:.2f}'.format(clf.best_score_)

best score : 0.83


In [45]:
# evaluate model
print 'score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test, y_test))

score for logistic regression - version 2 : 0.83


In [46]:
# confusion matrix
print 'confusion matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test)))

confusion matrix for baseline model: 
 [[110   0]
 [ 69   0]]


In [47]:
# confusion matrix
print 'confusion matrix for LR model: \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test)))

confusion matrix for LR model: 
 [[95 15]
 [15 54]]


In [48]:
# confusion matrix
print 'confusion matrix for optimised LR model: \n {0}'.format(confusion_matrix(y_test, clf.predict(X_test)))
#looks 1 worse on test data but does slightly better on predict / submission to kaggle

confusion matrix for optimised LR model: 
 [[94 16]
 [15 54]]


### Making Third Submission

In [49]:
# get submission file
##get_submission_file(clf, '03_lr.csv')

In [50]:
##!/home/kevin/anaconda3/envs/py27/bin/kaggle competitions submit -c titanic -f /home/kevin/Projects/titanic/data/external/03_lr.csv -m "Logistic Regression v2 - Tuned - l1"

### Feature Normalization and Standardization

In [51]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

#### Feature Normalization

In [52]:
# feature normalization
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [53]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(0.0, 1.0)

In [54]:
# normalize test data
X_test_scaled = scaler.transform(X_test)

#### Feature Standardization

In [60]:
# feature standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#### Create model after standardization

In [61]:
# base model 
model_lr = LogisticRegression(random_state=0)
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [62]:
clf.best_score_

0.8132022471910112

In [63]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [64]:
# evaluate model
print 'score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test_scaled, y_test))

score for logistic regression - version 2 : 0.84


In [65]:
# confusion matrix
print 'confusion matrix for standardised LR model: \n {0}'.format(confusion_matrix(y_test, clf.predict(X_test)))
#feature standardisation seems better (zero mean); normalisation (0 to 1, -1 to 1) has big 0s bias (not survived)

confusion matrix for standardised LR model: 
 [[106   4]
 [ 48  21]]


### Model Persistence

In [66]:
# import pickle library
import pickle

In [67]:
# create the file paths
model_file_path = os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir,'models','lr_scaler.pkl')

In [68]:
# open the files to write 
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [69]:
# persist the model and scaler
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [70]:
# close the file
model_file_pickle.close()
scaler_file_pickle.close()

#### load the persisted file

In [71]:
# open files in read mode
model_file_pickle = open(model_file_path, 'r')
scaler_file_pickle = open(scaler_file_path, 'r')
# load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
# close files
model_file_pickle.close()
scaler_file_pickle.close()

In [72]:
clf_loaded

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [73]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [74]:
# transform the test data using loaded scaler object
X_test_scaled = scaler_loaded.transform(X_test)
# calculate the score using loaded model object 
print 'score for persisted logistic regression : {0:.2f}'.format(clf_loaded.score(X_test_scaled, y_test))

score for persisted logistic regression : 0.84


In [75]:
# confusion matrix
print 'confusion matrix for standardised LR model: \n {0}'.format(confusion_matrix(y_test, clf.predict(X_test)))

confusion matrix for standardised LR model: 
 [[106   4]
 [ 48  21]]


### Third Kaggle Submission

In [78]:
def get_submission_file_with_standardization(model,filename, scaler):
    # converting to the matrix
#    test_X = test_df.as_matrix().astype('float')
    test_X = test_df.values.astype('float')
    # standardization
    test_X = scaler.transform(test_X)
    # make predictions
    predictions = model.predict(test_X)
    # submission dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
    # submission file
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path, filename)
    # write to the file
    df_submission.to_csv(submission_file_path, index=False)   

In [79]:
# get submission file
get_submission_file_with_standardization(clf, '04_lr.csv', scaler)

# feature standardization (see above)
scaler = StandardScaler()
or
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Random Forest Model

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
model_rf_1 = RandomForestClassifier(random_state=0, n_estimators=100)
model_rf_1.fit(X_train_scaled, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [83]:
# evaluate model
print 'score for random forest - version 1 : {0:.2f}'.format(model_rf_1.score(X_test_scaled, y_test))

score for random forest - version 1 : 0.82


In [84]:
# get submission file
get_submission_file_with_standardization(model_rf_1, '04_rf.csv', scaler)

In [85]:
# confusion matrix
print 'confusion matrix: \n {0}'.format(confusion_matrix(y_test, model_rf_1.predict(X_test_scaled)))

confusion matrix: 
 [[99 11]
 [22 47]]


### HyperParameter Tuning

In [86]:
from sklearn.model_selection import GridSearchCV

In [101]:
parameters = {'n_estimators':[10, 100, 200, 150, 250], 
              'min_samples_leaf':[1, 5,10,50, 3, 7],
              'max_features' : ('auto','sqrt','log2'),
             }
rf = RandomForestClassifier(random_state=0, oob_score=True)
clf = GridSearchCV(rf, parameters, cv=5)
#clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

#first pass: clf.best_params_ {'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 200}.  0.83
#second pass: {'max_features': 'auto', 'min_samples_leaf': 7, 'n_estimators': 100}  0.83

In [102]:
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=True, random_state=0, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [10, 100, 200, 150, 250], 'max_features': ('auto', 'sqrt', 'log2'), 'min_samples_leaf': [1, 5, 10, 50, 3, 7]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [103]:
clf.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=7, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=True, random_state=0, verbose=0, warm_start=False)

In [105]:
clf.best_params_

{'max_features': 'auto', 'min_samples_leaf': 7, 'n_estimators': 100}

In [106]:
# best score
print 'best score for random forest : {0:.2f}'.format(clf.best_score_)

best score for random forest : 0.83


In [107]:
# confusion matrix
print 'confusion matrix: \n {0}'.format(confusion_matrix(y_test, clf.predict(X_test)))

confusion matrix: 
 [[100  10]
 [ 20  49]]


In [108]:
# get submission file
get_submission_file(clf, '05_rf.csv')

### Confusion Metrics , Precision and Recall

In [109]:
from sklearn.preprocessing import MinMaxScaler

In [110]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
model = LogisticRegression()

In [113]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [114]:
from sklearn import metrics

In [115]:
model.score(X_test, y_test)

0.8268156424581006

In [116]:
pred = model.predict(X_test)
fpr, tpr, thresholds = metrics.roc_curve(y_test, pred)
metrics.auc(fpr, tpr)

0.8158761528326746

In [117]:
# Predict on Final Test data

In [119]:
test_X = test_df.values.astype('float')

In [120]:
test_X = scaler.transform(test_X)

In [121]:
predictions = model.predict_proba(test_X)

In [122]:
print predictions.shape

(418, 2)


In [125]:
print predictions

[[0.89406578 0.10593422]
 [0.43265986 0.56734014]
 [0.82768001 0.17231999]
 [0.91318311 0.08681689]
 [0.31978926 0.68021074]
 [0.85868924 0.14131076]
 [0.33284987 0.66715013]
 [0.88942798 0.11057202]
 [0.18843    0.81157   ]
 [0.95126285 0.04873715]
 [0.91954613 0.08045387]
 [0.78071379 0.21928621]
 [0.07431248 0.92568752]
 [0.92021733 0.07978267]
 [0.03974827 0.96025173]
 [0.1287065  0.8712935 ]
 [0.754725   0.245275  ]
 [0.86304049 0.13695951]
 [0.46211798 0.53788202]
 [0.26534032 0.73465968]
 [0.75046131 0.24953869]
 [0.40357959 0.59642041]
 [0.09745879 0.90254121]
 [0.63230281 0.36769719]
 [0.08845008 0.91154992]
 [0.96118853 0.03881147]
 [0.07722602 0.92277398]
 [0.8659162  0.1340838 ]
 [0.68421636 0.31578364]
 [0.9333981  0.0666019 ]
 [0.90313587 0.09686413]
 [0.88002109 0.11997891]
 [0.47552562 0.52447438]
 [0.48276234 0.51723766]
 [0.67999878 0.32000122]
 [0.85813181 0.14186819]
 [0.38159203 0.61840797]
 [0.37755104 0.62244896]
 [0.91046444 0.08953556]
 [0.9245609  0.0754391 ]
